site:
  title: WB Docs Demo
  start_page: ru:ROOT:wiren-board-7.adoc
content:
  sources:
  - url: https://gitlab.com/antora/demo/demo-component-a.git
    branches: HEAD
  - url: https://gitlab.com/antora/demo/demo-component-b.git
    branches: [v2.0, v1.0]
    start_path: docs
  - url: https://github.com/poglazov/poglazov.github.io.git
    start_paths:
    - docs/en
    - docs/ru
  
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
    
antora:
  extensions:
  - require: '@antora/lunr-extension'
    languages: [en, ru]
